language: node_js
node_js:
    - "6"
    - "10"
before_install:
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc
  - git config --global url.https://$GITHUB_TOKEN:x-oauth-basic@github.com/.insteadOf ssh://git@github.com/
